import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
//import ThemeProvider from "./context/ThemeProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/session";
import { Providers } from "./providers";
import Header from "@/components/Headers/header";
import Footer from "../components/Footers/footer";
import RegisterModal from "@/components/modals/RegisterModal";
import LoginModal from "@/components/modals/LoginModal";
import BoutonTelecharger from "@/components/Boutons/BoutonTelecharger";
import FooterNew from "@/components/Footers/footerNew";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Makoya",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* <ThemeProvider> */}
        <div className="px-4 md:px-10 lg:px-12">
          {" "}
          {/* Utilisation de padding responsive */}
          <RegisterModal />
          <LoginModal />
          <Providers session={session}>
            <Header />
            {children}
            <FooterNew />
          </Providers>
          <div
            id="container-floating"
            className="fixed bottom-0 right-0 p-4 md:p-8 lg:p-12"
          >
            {" "}
            {/* Utilisation de padding et positionnement responsive */}
            <div id="floating-button">
              <BoutonTelecharger />
            </div>
          </div>
        </div>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
